[tool.poetry]
name = "tiingo_client"
version = "0.1.0"
description = ""
authors = ["Andrew Rainboldt <arainboldt@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
async-mixin = "0.0.2"
pandas = "^1.3.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
