[tool.poetry]
name = "inxi"
version = "0.1.0"
description = "A Python template project"
authors = ["Jan Willems <jw@elevenbits.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
typer = "^0.4.0"
psutil = "^5.8.0"
py-cpuinfo = "^8.0.0"
rich = "^10.16.1"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
pre-commit = "^2.16.0"
isort = "^5.10.1"
flake8 = "^4.0.1"
ipython = "^7.30.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
