[build-system]
requires = [ "flit_core >=3.2,<4" ]
build-backend = "flit_core.buildapi"

[project]
name = "formbox"
version = "0.0.1"
description = "Format mbox as HTML/XML"
readme = "README.md"
requires-python = ">=3.7"
license = { file = "COPYING" }
authors = [ { name = "Nguyễn Gia Phong", email = "mcsinyx@disroot.org" } ]
maintainers = [ { name = "Nguyễn Gia Phong", email = "mcsinyx@disroot.org" } ]
keywords = [ "email", "format", "html", "mbox", "template", "xml" ]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Utilities" ]
dependencies = [ "bleach", "markdown" ]
urls = { Git = "https://git.sr.ht/~cnx/formbox" }
