[tool.poetry]
name = "metadoctor"
version = "0.1.3"
description = ""
authors = ["arantesdv <arantesdv@me.com>"]

[tool.poetry.dependencies]
python = "^3.9"
starlette = "^0.17.1"
deta = "^1.0.1"
MarkupSafe = "^2.0.1"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
