[tool.poetry]
name = "shared_dependencies"
version = "0.1.1"
description = ""
authors = ["Jean-Charles Bouchaud <jeancharles-b@evidenceb.com>"]

[tool.poetry.dependencies]
python = "^3.10"
httpx = "^0.21.1"
colorama = "^0.4.4"
sentry-sdk = "^1.5.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-asyncio = "^0.16.0"
pytest-httpx = "^0.17.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
