[tool.poetry]
name = "uMonitor"
version = "0.1.5"
description = "A package to run and monitor background services"
authors = ["Ruslan Sergeev <mybox.sergeev@gmail.com>"]
keywords = ["microservices", "monitor", "scheduler"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/RuslanSergeev/uMonitor.git"
repository = "https://github.com/RuslanSergeev/uMonitor.git"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
